name: visjs_library
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: R.Dulkarnaev <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
